name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to server
      env:
        API_KEY: ${{ secrets.API_KEY }}
        APPID: ${{ secrets.APPID }}
        AUTHDOMAIN: ${{ secrets.AUTHDOMAIN }}
        MESSAGINGSENDERID: ${{ secrets.MESSAGINGSENDERID }}
        PROJECTID: ${{ secrets.PROJECTID }}
        STORAGEBUCKET: ${{ secrets.STORAGEBUCKET }}
      run: |
        echo "Deploying with API_KEY: $API_KEY"
        # Hier kannst du deinen Deployment-Befehl hinzufügen
